---
version: "3.7"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - proxy
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NAME_SERVERS=${NAME_SERVERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/config
      - ${FILE2}:/plex
    restart: unless-stopped


networks:
  proxy:
    external: true