---
version: "3.7"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:${TAG}
    container_name: sonarr
    networks:
      - proxy
    ports:
      - ${APP_PORT}:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NAME_SERVERS=${NAME_SERVERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/sonarr/config:/config
      - /media/plex:/plex
    restart: unless-stopped


networks:
  proxy:
    external: true