---
version: "3.8"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${FILE1}:/config
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
        mode: ingress
    networks:
      - cloudflare
networks:
  cloudflare:
    external: true