---
version: "3.9"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${FILE1}:/config
      - /etc/localtime:/etc/localtime:ro 
    networks:
      - cloudflare
    ports:
      - 8181:8181

networks:
  cloudflare:
    external: true