---
version: "3.9"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NAME_SERVERS=${NAME_SERVERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/config
    ports:
      - 9696:9696
<<<<<<< HEAD
    restart: unless-stopped
=======
    restart: unless-stopped
>>>>>>> 79432099951b88007b560e30f5b3c5fcdf2ffdf7
