version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - VERSION=docker
      - 'ADVERTISE_IP=https://${IP_ADDRESS}:32400/'
      - PLEX_CLAIM=${PLEX_CLAIM}
      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - plex_config:/config
      - plex_dev:/dev/shm
      - ${FILE1}:/media

volumes:
  plex_config:
    external: true
  plex_dev:
    external: true