---
version: "3.7"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ~/vm/duplicati/config:/config
      - ~/vm/share/duplicati/trust:/backups
      - ~/vm:/source
    networks:
      - proxy
    ports:
      - 8200:8200
    restart: unless-stopped

networks:
  proxy:
    external: true