---
version: "3.7"
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs
    container_name: wikijs
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NAME_SERVERS=${NAME_SERVERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/wiki/config:/config
      - ~/vm/wiki/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped

networks:
  proxy:
    external: true 