---
version: "3.7"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - "NAME_SERVERS=${NAME_SERVERS}"
    ports:
     - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - radarr:/config
      - ${FILE1}:/plex
    restart: unless-stopped


networks:
  proxy:
    external: true

volumes:
  radarr:
    external: true