---
version: '3.8'

services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgresql
    restart: unless-stopped
    networks:
      - authentik
    volumes:
      - ${FILE1}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}


  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - authentik


  server:
    image: ghcr.io/goauthentik/server
    container_name: server
    restart: unless-stopped
    networks:
      - proxy
      - authentik
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # WORKERS: 2
    volumes:
      - ${FILE2}:/media
      - ${FILE3}:/templates
      - ${FILE4}:/geoip
    ports:
      - "0.0.0.0:9001:9000"
      - "0.0.0.0:9443:9443"


  worker:
    image: ghcr.io/goauthentik/server
    container_name: worker
    restart: unless-stopped
    networks:
      - authentik
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore
    user: ${USER1}
    volumes:
      - ${FILE2}:/media
      - ${FILE5}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ${FILE3}:/templates
      - ${FILE4}:/geoip
 
  
  geoipupdate:
    image: "maxmindinc/geoipupdate:latest"
    container_name: geoipupdate
    networks:
      - authentik
    volumes:
      - "${FILE4}:/usr/share/GeoIP"
    environment:
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: "8"

networks:
  proxy:
    external: true
  authentik:
    external: true