---
version: "3.9"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${USER}
      - OPENVPN_PASSWORD=${PASS}
      - SERVER_REGIONS=${REGION}
      - TZ=${TZ}


    qbittorrent:
      image: linuxserver/qbittorrent
      container_name: qbittorrent
      network_mode: "service:gluetun"
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - UMASK_SET=022
        - WEBUI_PORT=8080
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - qbit:/config
        - ${FILE1}:/downloads
      restart: unless-stopped


volumes:
  qbit:
    external: true
  gluetun:
    external: true 