---
version: "3.9"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${USER}
      - OPENVPN_PASSWORD=${PASS}
      - SERVER_REGIONS=${REGION}
      - TZ=${TZ}


    qbittorrent:
      image: linuxserver/qbittorrent
      container_name: qbittorrent
      network_mode: "service:gluetun"
      environment:
        - PUID=998
        - PGID=100
        - TZ=America/Denver
        - UMASK_SET=022
        - WEBUI_PORT=8080
      volumes:
        - /srv/dev-disk-by-label-Files/Configs/QBittorrent:/config
        - /srv/dev-disk-by-label-Files/Storage:/downloads
      restart: unless-stopped



networks:
  proxy:
    external: true

volumes:
  qbit:
    external: true 