version: "3.9"
services:
  alpine-qbittorrent-openvpn:
    container_name: qbit
    image: guillaumedsde/alpine-qbittorrent-openvpn
    volumes:
      - "${FILE1}:/downloads"
      - "qbit2:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - LAN=192.168.0.0/16
      - LOCAL_NETWORK=10.10.0.0/16
      - TUN=/dev/net/tun
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN

volumes:
  qbit2:
    external: true
