---
version: '3.7'
services:
    qbit:
      image: markusmcnugen/qbittorrentvpn:${TAG}
      container_name: qbit
      volumes:
        - ~/vm/qbit/config:/config
        - /media/plex/new_downloads:/downloads
      restart: unless-stopped
      networks:
        - proxy
      environment:
        - "VPN_ENABLED=yes"
        - "LAN_NETWORK=${LAN_NETWORK}"
        - "LAN_NETWORK=${LAN_NETWORK2}"
        - "NAME_SERVERS=${NAME_SERVERS}"
        - "WEBUI_PORT_ENV=${WEBUI_PORT_ENV}"
        - "PGID=${PGID}"
        - "PUID=${PUID}"      
      cap_add: 
        - NET_ADMIN
      devices:
        - /dev/net/tun            
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_LABEL}.entrypoints=http"
      - "traefik.http.routers.${TRAEFIK_LABEL}.rule=Host(`${FQDN}`)"
      - "traefik.http.middlewares.${TRAEFIK_LABEL}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${TRAEFIK_LABEL}.middlewares=portainer-https-redirect"
      - "traefik.http.routers.${TRAEFIK_LABEL}-secure.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_LABEL}-secure.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.${TRAEFIK_LABEL}-secure.tls=true"
      - "traefik.http.routers.${TRAEFIK_LABEL}-secure.service=${TRAEFIK_LABEL}"
      - "traefik.http.services.${TRAEFIK_LABEL}.loadbalancer.server.port=${APP_PORT}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true 