---
version: "3.9"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - qbit:/config
      - ${FILE1}:/downloads
    restart: unless-stopped


volumes:
  qbit:
    external: true