---
version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${FILE1}:/app/data/configs
      - ${FILE2}:/app/public/icons
    ports:
      - '7575:7575'
