---
version: "3.7"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jackett:/config
      - ${FILE2}:/downloads
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - AUTO_UPDATE=true #optional
      - NAMESERVER=${NAMESERVER}
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  jackett:
    external: true