---
version: "3.7"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:${TAG}
    container_name: jackett
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/jackett/config:/config
      - /media/plex/ndown:/downloads
    restart: unless-stopped
    ports:
      - ${APP_PORT}:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - AUTO_UPDATE=true #optional
      - NAMESERVER=${NAMESERVER}
    networks:
      - proxy

networks:
  proxy:
    external: true 