---
version: "3.7"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ~/vm/homer/assets:/www/assets
    networks:
      - proxy
    ports:
      - ${APP_PORT}:8080
    restart: unless-stopped


networks:
  proxy:
    external: true