---
version: "3.7"
services:
  nginx1:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/config
    restart: unless-stopped
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
