version: '3.7'
services:
  cloudflare-DDNS1:
    container_name: cf1
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - API_KEY=${API_KEY1}
      - ZONE=${ZONE1}
      - PROXIED=true
  cloudflare-DDNS2:
    container_name: cf2
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - API_KEY=${API_KEY2}
      - ZONE=${ZONE2}
      - PROXIED=true