version: '3.7'
services:
  cloudflare-DDNS1:
    container_name: cloudflare_ip
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - API_KEY=${API_KEY}
      - ZONE=${ZONE1}
      - PROXIED=true
