---
version: "3.9"
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    network_mode: "service:gluetun"
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NZBGET_USER=${USER} #optional
      - NZBGET_PASS=${PASS} #optional
    volumes:
      - ${FILE1}:/config
      - ${FILE2}:/downloads #optional
    restart: unless-stopped