version: "3.7"

services:
  minecraft:
    image: minecraftservers/minecraft-server
    container_name: minecraft
    ports:
      - ${APP_PORT}:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ~/vm/minecraft/minecraft-data:/data