---
version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true