---
version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ~/vm/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true