---
version: "3.9"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.31.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${FILE1}:/gluetun
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 6789:6789/udp #nzbget
      - 6789:6789/tcp #nzbget
      - 8080:8080 #qbit
      - 6881:6881 #qbit
      - 6881:6881/udp #qbit
    environment:
      - VPN_SERVICE_PROVIDER=${PROVIDER}
      - OPENVPN_USER=${USER}
      - OPENVPN_PASSWORD=${PASS}
      - SERVER_REGIONS=${REGION}
      - TZ=${TZ}
