---
version: "3.7"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    networks:
      - proxy
      - syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/syncthing/config:/config
      - ~/vm:/vm

    restart: unless-stopped

networks:
  proxy:
    external: true
  syncthing:
    external: true