---
version: "3.7"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:${TAG}
    container_name: syncthing
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/syncthing/config:/config
      - ~/vm:/vm
    ports:
      - ${APP_PORT}:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

    restart: unless-stopped

networks:
  proxy:
    external: true