version: "3.7"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_SCHEDULE= 0 0 4 * * *
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}"
      - "WATCHTOWER_NOTIFICATION_URL=ntfy://${URL}${TOPIC}?title=WatchtowerUpdates"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro